// Generated by CoffeeScript 1.10.0
(function() {
  var CND, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MULTIMIX/COPIERS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  this.dont = function(x, seen) {
    throw new Error("unable to copy value of type " + (CND.type_of(x)));
  };

  this.id = function(x, seen) {
    seen.set(x, x);
    return x;
  };

  this.object = function(x, seen) {

    /* shamelessly copied from https://github.com/nrn/universal-copy */
    var R;
    R = Object.create(Object.getPrototypeOf(x));
    seen.set(x, R);
    if (Object.isFrozen(x)) {
      Object.freeze(R);
    }
    if (Object.isSealed(x)) {
      Object.seal(R);
    }
    if (!Object.isExtensible(x)) {
      Object.preventExtensions(R);
    }
    return R;
  };

  this.by_constructor = function(x, seen) {

    /* shamelessly copied from https://github.com/nrn/universal-copy */
    var R;
    R = new x.constructor(x);
    seen.set(x, R);
    return R;
  };

}).call(this);

//# sourceMappingURL=copiers.js.map
