// Generated by CoffeeScript 1.10.0
(function() {
  var CND, MULTIMIX, alert, badge, debug, echo, help, info, join, log, rpr, urge, warn, whisper, σ_finalize, σ_new_state, σ_reject,
    slice = [].slice;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MULTIMIX';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  join = require('path').join;

  σ_new_state = Symbol["for"]('new_state');

  σ_reject = Symbol["for"]('reject');

  σ_finalize = Symbol["for"]('finalize');

  MULTIMIX = {};

  MULTIMIX.TOOLS = require('./tools');

  MULTIMIX.REDUCERS = require('./reducers');

  MULTIMIX.mix = function(me, reducers, mixins, root, selector) {
    var R, S, i, j, len, len1, mixin, mx_key, mx_value, partial_mixin, partial_mixins, rd_key, rd_value, reducer, ref;
    if (root == null) {
      root = null;
    }
    if (selector == null) {
      selector = [];
    }
    if (!(mixins.length > 0)) {
      return null;
    }

    /* TAINT support multiple types at all or only PODs? */
    R = CND.isa_list(mixins[0]) ? [] : {};
    S = me.REDUCERS[σ_new_state](reducers);
    if (root == null) {
      root = R;
    }

    /* Deal with nested reducers first: */
    for (rd_key in reducers) {
      rd_value = reducers[rd_key];
      if (CND.isa_pod(rd_value)) {
        selector.push(rd_key);
        partial_mixins = [];
        for (i = 0, len = mixins.length; i < len; i++) {
          mixin = mixins[i];
          partial_mixin = mixin[rd_key];
          if (partial_mixin != null) {
            partial_mixins.push(partial_mixin);
          }
        }
        if (partial_mixins.length > 0) {
          R[rd_key] = MULTIMIX.mix(me, rd_value, partial_mixins, root, selector);
        }
        reducers[rd_key] = 'skip';
        selector.pop(rd_key);
      }
    }

    /* Process unnested reducers: */
    for (j = 0, len1 = mixins.length; j < len1; j++) {
      mixin = mixins[j];
      for (mx_key in mixin) {
        mx_value = mixin[mx_key];
        S.path = join.apply(null, slice.call(selector).concat([mx_key]));
        S.root = root;
        S.current = R;
        S.reducer_name = (ref = S.reducers[mx_key]) != null ? ref : S.reducer_fallback;
        if (me.REDUCERS[σ_reject](S, mx_key, mx_value)) {
          continue;
        }
        if ((reducer = me.REDUCERS[S.reducer_name]) == null) {
          throw new Error("unknown reducer " + (rpr(S.reducer_name)));
        }
        reducer.call(me.REDUCERS, S, mx_key, mx_value);
      }
    }
    me.REDUCERS[σ_finalize](S);
    return R;
  };

  MULTIMIX.use = function() {
    var R, custom_reducers, reducers;
    custom_reducers = 1 <= arguments.length ? slice.call(arguments, 0) : [];

    /* Returns a version of `mix` that uses the reducers passed in to `use`; the resulting reducer is
    derived from the reducers list by applying `mix`. Turtles.
     */
    custom_reducers.splice(0, 0, {
      '*': 'assign'
    });
    reducers = MULTIMIX.mix(MULTIMIX, null, custom_reducers);
    R = function() {
      var mixins;
      mixins = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return MULTIMIX.mix(R, reducers, mixins);
    };
    R.TOOLS = MULTIMIX.TOOLS;
    R.REDUCERS = MULTIMIX.REDUCERS;
    R.use = MULTIMIX.use;
    R.deep_copy = function(x) {
      return CND.deep_copy(x);
    };
    return R;
  };

  module.exports = {
    mix: MULTIMIX.use()
  };

}).call(this);

//# sourceMappingURL=main.js.map
