// Generated by CoffeeScript 1.10.0
(function() {
  var CND, alert, badge, debug, echo, help, info, log, rpr, urge, warn, whisper;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MULTIMIX/REDUCERS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  this.merge = function(S, R, key, value) {
    var sub_key, sub_value, target;
    if (!CND.isa_pod(value)) {
      throw new Error("expected a POD, got a " + (CND.type_of(value)));
    }
    target = (R[key] != null ? R[key] : R[key] = {});
    for (sub_key in value) {
      sub_value = value[sub_key];
      target[sub_key] = sub_value;
    }
    return null;
  };

}).call(this);

//# sourceMappingURL=reducers.js.map
