// Generated by CoffeeScript 1.10.0
(function() {
  var CND, alert, badge, debug, echo, help, include, info, log, mix, rpr, s, t, test, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MULTIMIX/TESTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  test = require('guy-test');

  mix = require('./main').mix;

  s = function(x) {
    return JSON.stringify(x, null, '  ');
  };

  t = function(x) {
    return JSON.stringify(x);
  };

  this._prune = function() {
    var name, value;
    for (name in this) {
      value = this[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  this._main = function() {
    return test(this, {
      'timeout': 3000
    });
  };

  this["demo (1)"] = function(T) {
    var a, b, my_mix, test_tools;
    test_tools = function(T, x) {
      var i, key, len, ref;
      if (x.tools == null) {
        return T.fail("object has no property 'tools'");
      }
      ref = ['normalize_tag', 'unique', 'append', 'meld', 'reduce_tag'];
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        T.ok(x.tools[key] != null);
      }
      return null;
    };
    test_tools(T, mix);
    my_mix = mix.use({
      primes: 'append'
    });
    test_tools(T, my_mix);
    a = {
      id: 'a',
      primes: [2, 3, 5, 7],
      report: function() {
        return t({
          id: this.id,
          primes: this.primes
        });
      }
    };
    b = my_mix(a, {
      id: 'b',
      primes: [13, 17, 23]
    });
    info('©09344', mix);
    urge('©45237', my_mix);
    info('©82977', 'a', a);
    urge('©56112', 'b', b);
    T.eq(a['primes'], [2, 3, 5, 7]);
    T.eq(b['primes'], [2, 3, 5, 7, 13, 17, 23]);
    T.eq(a.report(), '{"id":"a","primes":[2,3,5,7]}');
    T.eq(b.report(), '{"id":"b","primes":[2,3,5,7,13,17,23]}');
    return null;
  };

  if (module.parent == null) {
    include = ["demo (1)"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=tests.js.map
