// Generated by CoffeeScript 1.10.0
(function() {
  var CND, alert, badge, debug, echo, help, include, info, log, mix, rpr, s, t, test, urge, warn, whisper,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MULTIMIX/TESTS';

  log = CND.get_logger('plain', badge);

  info = CND.get_logger('info', badge);

  whisper = CND.get_logger('whisper', badge);

  alert = CND.get_logger('alert', badge);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  echo = CND.echo.bind(CND);

  test = require('guy-test');

  mix = require('./main').mix;

  s = function(x) {
    return JSON.stringify(x, null, '  ');
  };

  t = function(x) {
    return JSON.stringify(x);
  };

  this._prune = function() {
    var name, value;
    for (name in this) {
      value = this[name];
      if (name.startsWith('_')) {
        continue;
      }
      if (indexOf.call(include, name) < 0) {
        delete this[name];
      }
    }
    return null;
  };

  this._main = function() {
    return test(this, {
      'timeout': 3000
    });
  };

  this["demo (1)"] = function(T) {
    var a, b, my_mix, test_tools;
    test_tools = function(T, x) {
      var i, key, len, ref;
      if (x.tools == null) {
        return T.fail("object has no property 'tools'");
      }
      ref = ['normalize_tag', 'unique', 'append', 'meld', 'reduce_tag'];
      for (i = 0, len = ref.length; i < len; i++) {
        key = ref[i];
        T.ok(x.tools[key] != null);
      }
      return null;
    };
    test_tools(T, mix);
    my_mix = mix.use({
      primes: 'append'
    });
    test_tools(T, my_mix);
    a = {
      id: 'a',
      primes: [2, 3, 5, 7],
      report: function() {
        return t({
          id: this.id,
          primes: this.primes
        });
      }
    };
    b = my_mix(a, {
      id: 'b',
      primes: [13, 17, 23]
    });
    T.eq(a['primes'], [2, 3, 5, 7]);
    T.eq(b['primes'], [2, 3, 5, 7, 13, 17, 23]);
    T.eq(a.report(), '{"id":"a","primes":[2,3,5,7]}');
    T.eq(b.report(), '{"id":"b","primes":[2,3,5,7,13,17,23]}');
    return null;
  };

  this["options example (1)"] = function(T) {
    var options, options_base, options_user;
    options_base = {
      zoom: '125%',
      paths: {
        app: '~/sample',
        fonts: '~/.fonts'
      },
      fonts: {
        files: {
          'Arial': 'HelveticaNeue.ttf'
        },
        sizes: {
          unit: 'pt',
          steps: [8, 10, 11, 12, 14, 16, 18, 24]
        }
      }
    };
    options_user = {
      zoom: '85%',
      fonts: {
        files: {
          'ComicSans': 'MSComicSans.ttf'
        }
      }
    };
    options = mix(options_base, options_user);
    T.ok(options['paths'] === options_base['paths']);
    T.ok(options['fonts'] === options_user['fonts']);
    T.eq(options['zoom'], options_user['zoom']);
    return null;
  };

  this["options example (2)"] = function(T) {
    var mix_options, options, options_base, options_user, reducers;
    options_base = {
      primes: [2, 3, 5],
      zoom: '125%',
      paths: {
        app: '~/sample',
        fonts: '~/.fonts'
      },
      fonts: {
        files: {
          'Arial': 'HelveticaNeue.ttf'
        },
        sizes: {
          unit: 'pt',
          steps: [8, 10, 11, 12, 14, 16, 18, 24]
        }
      },
      words: {
        foo: 3,
        bar: 3
      }
    };
    options_user = {
      primes: [7, 11, 13],
      zoom: '85%',
      fonts: {
        files: {
          'ComicSans': 'MSComicSans.ttf'
        }
      },
      words: {
        supercalifragilistic: 20
      }
    };
    reducers = {
      primes: 'append',
      words: 'merge',
      zoom: function(zoom_percentages) {
        var R, i, len, percentage;
        R = 1;
        for (i = 0, len = zoom_percentages.length; i < len; i++) {
          percentage = zoom_percentages[i];
          R *= (parseFloat(percentage)) / 100;
        }
        return ((R * 100).toFixed(2)) + "%";
      }
    };
    mix_options = mix.use(reducers);
    options = mix_options(options_base, options_user);
    urge('5543', options);
    T.ok(options['paths'] === options_base['paths']);
    T.ok(options['fonts'] === options_user['fonts']);
    T.eq(options['primes'], [2, 3, 5, 7, 11, 13]);
    T.eq(options['zoom'], '106.25%');
    return null;
  };

  if (module.parent == null) {
    include = ["demo (1)", "options example (1)", "options example (2)"];
    this._prune();
    this._main();
  }

}).call(this);

//# sourceMappingURL=tests.js.map
